### ISSUE TITLE
报错：Could not find the input entity for <telethon.tl.types.PeerChannel object at 0x107fe2630>.

### ISSUE THREAD

**Issue by V-know** [QuantumGhost/ncov-channel-crawler#2]
执行: python login.py报错如下：

2020-03-20 11:24.42 telethon session               session=covid-19
2020-03-20 11:24.42 before telegram client start
2020-03-20 11:24.43 telegram client started
2020-03-20 11:24.43 start polling
2020-03-20 11:24.43 retriece messages with last_id last_id=1
Traceback (most recent call last):
  File "login.py", line 17, in <module>
    main()
  File "login.py", line 13, in main
    loop.run_until_complete(crawler.start_poll())
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 573, in run_until_complete
    return future.result()
  File "/Users/Gavin/python3/Covid-19/ncov-channel-crawler/crawler/crawler.py", line 106, in start_poll
    more = await self._poll()
  File "/Users/Gavin/python3/Covid-19/ncov-channel-crawler/crawler/crawler.py", line 77, in _poll
    PeerChannel(self._CHANNEL_ID), min_id=last_id, limit=100, reverse=True,
  File "/Users/Gavin/python3/Covid-19/ncov-channel-crawler/venv/lib/python3.7/site-packages/telethon/client/messages.py", line 531, in get_messages
    return await it.collect()
  File "/Users/Gavin/python3/Covid-19/ncov-channel-crawler/venv/lib/python3.7/site-packages/telethon/requestiter.py", line 114, in collect
    async for message in self:
  File "/Users/Gavin/python3/Covid-19/ncov-channel-crawler/venv/lib/python3.7/site-packages/telethon/requestiter.py", line 58, in __anext__
    if await self._init(**self.kwargs):
  File "/Users/Gavin/python3/Covid-19/ncov-channel-crawler/venv/lib/python3.7/site-packages/telethon/client/messages.py", line 25, in _init
    self.entity = await self.client.get_input_entity(entity)
  File "/Users/Gavin/python3/Covid-19/ncov-channel-crawler/venv/lib/python3.7/site-packages/telethon/client/users.py", line 437, in get_input_entity
    .format(peer)
ValueError: Could not find the input entity for <telethon.tl.types.PeerChannel object at 0x107fe2630>. Please read https://docs.telethon.dev/en/latest/concepts/entities.html to find out more details.

**Comment by QuantumGhost** [comment]
我没有遇到过这种问题，请问你是修改了代码么
